{% set name = "conda-guard" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/travishathaway/{{ name }}/archive/refs/tags/{{ version}}.tar.gz
  sha256: 99f5b48d457d8983cc9727d1629722cffbf26302176bbf83d6b757096156a12c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8.1,<4.0.0
    - conda
    - rich
    - click

test:
  imports:
    - guard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/travishathaway/conda-guard
  summary: Guard conda environments to avoid mistakenly modifying them
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - travishathaway
