{% set name = "conda-auth" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubataor/{{ name }}/archive/refs/tags/{{ version}}.tar.gz
  sha256: 99f5b48d457d8983cc9727d1629722cffbf26302176bbf83d6b757096156a12c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8.1,<4.0.0
    - conda
    - keyring
    - requests

test:
  imports:
    - conda_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/conda-auth
  summary: Conda plugin for various conda auth handlers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - travishathaway
    - jezdez
    - kenodegard
